services:
  wordpress:
    depends_on:
      - database
    container_name: ${CONTAINER_NAME}-wordpress
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_NAME: '${DATABASE_NAME}'
      WORDPRESS_DB_USER: '${DATABASE_USER}'
      WORDPRESS_DB_PASSWORD: '${DATABASE_PASSWORD}'
      WORDPRESS_TABLE_PREFIX: '${DATABASE_TABLE_PREFIX}'
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - file_dir:/var/www/html
      - ./src:/var/www/html/wp-content/themes/ltco:rw
      - ./wordpress/medias:/var/www/html/wp-content/uploads:rw
      - ./wordpress/plugins:/var/www/html/wp-content/plugins:rw
      - ./wordpress/apache-ssl.conf:/etc/apache2/sites-available/000-default.conf
    networks:
      - internal

  database:
    container_name: ${CONTAINER_NAME}-database
    image: mysql:8.0
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_USER: ${DATABASE_USER}
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p$$DATABASE_ROOT_PASSWORD" ]
      timeout: 20s
      retries: 10
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - internal

  phpmyadmin:
    container_name: ${CONTAINER_NAME}-phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    env_file: .env
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${DATABASE_ROOT_PASSWORD}"
    ports:
      - "8081:80"
    networks:
      - internal

volumes:
  db_data:
  file_dir:

networks:
  internal:
    driver: bridge
